language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
install:
  - cargo benchcmp --version || cargo install cargo-benchcmp
cache: cargo
after_script:
  - ./travis-after-script.sh
